"""initial observability schema

Revision ID: dc1b7cbfdafe
Revises:
Create Date: 2026-07-29 21:22:16.095753
"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision = "dc1b7cbfdafe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "data_licences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("raw_storage_allowed", sa.Boolean(), nullable=False),
        sa.Column("redistribution_allowed", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("data_mode", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_data_sources_data_mode"), "data_sources", ["data_mode"], unique=False)
    op.create_table(
        "national_snapshots",
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_mode", sa.String(length=32), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("in_use", sa.Integer(), nullable=False),
        sa.Column("out_of_service", sa.Integer(), nullable=False),
        sa.Column("stale_unknown", sa.Integer(), nullable=False),
        sa.Column("inventory_connectors", sa.Integer(), nullable=False),
        sa.Column("reported_connectors", sa.Integer(), nullable=False),
        sa.Column("fresh_connectors", sa.Integer(), nullable=False),
        sa.Column("hpc_available", sa.Integer(), nullable=False),
        sa.Column("utilization", sa.Float(), nullable=True),
        sa.Column("normal_utilization", sa.Float(), nullable=True),
        sa.Column("pressure_score", sa.Integer(), nullable=True),
        sa.Column("pressure_components", sa.JSON(), nullable=False),
        sa.Column("serious_incidents", sa.Integer(), nullable=False),
        sa.Column("recovered_last_hour", sa.Integer(), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("bucket_start", "data_mode"),
    )
    op.create_table(
        "region_snapshots",
        sa.Column("bundesland", sa.String(length=64), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_mode", sa.String(length=32), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("in_use", sa.Integer(), nullable=False),
        sa.Column("out_of_service", sa.Integer(), nullable=False),
        sa.Column("stale_unknown", sa.Integer(), nullable=False),
        sa.Column("inventory_connectors", sa.Integer(), nullable=False),
        sa.Column("utilization", sa.Float(), nullable=True),
        sa.Column("pressure_score", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("bundesland", "bucket_start", "data_mode"),
    )
    op.create_table(
        "reliability_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uptime", sa.Float(), nullable=True),
        sa.Column("observable_share", sa.Float(), nullable=False),
        sa.Column("outage_count", sa.Integer(), nullable=False),
        sa.Column("median_outage_minutes", sa.Float(), nullable=True),
        sa.Column("mttr_minutes", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reliability_metrics_scope_id"), "reliability_metrics", ["scope_id"], unique=False
    )
    op.create_table(
        "operators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "external_id"),
    )
    op.create_index(op.f("ix_operators_name"), "operators", ["name"], unique=False)
    op.create_table(
        "source_publications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("licence_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=True),
        sa.Column("delivery_mode", sa.String(length=32), nullable=False),
        sa.Column("publication_type", sa.String(length=32), nullable=False),
        sa.Column("supports_delta", sa.Boolean(), nullable=False),
        sa.Column("update_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("stale_after_seconds", sa.Integer(), nullable=False),
        sa.Column("rate_limit_notes", sa.Text(), nullable=True),
        sa.Column("storage_rights_verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["data_licences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_source_publications_data_source_id"),
        "source_publications",
        ["data_source_id"],
        unique=False,
    )
    op.create_table(
        "charging_sites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("bundesland", sa.String(length=64), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("corridor", sa.Boolean(), nullable=False),
        sa.Column("data_mode", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
        ),
        sa.ForeignKeyConstraint(["publication_id"], ["source_publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_id", "external_id"),
    )
    op.create_index(
        op.f("ix_charging_sites_bundesland"), "charging_sites", ["bundesland"], unique=False
    )
    op.create_index(
        op.f("ix_charging_sites_data_mode"), "charging_sites", ["data_mode"], unique=False
    )
    op.create_index(
        "ix_charging_sites_geom", "charging_sites", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        op.f("ix_charging_sites_operator_id"), "charging_sites", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_charging_sites_publication_id"), "charging_sites", ["publication_id"], unique=False
    )
    op.create_table(
        "feed_health_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_seconds", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["publication_id"], ["source_publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feed_health_observations_observed_at"),
        "feed_health_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feed_health_observations_publication_id"),
        "feed_health_observations",
        ["publication_id"],
        unique=False,
    )
    op.create_table(
        "raw_payload_envelopes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=True),
        sa.Column("publication_mode", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=True),
        sa.Column("retained", sa.Boolean(), nullable=False),
        sa.Column("retention_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["publication_id"], ["source_publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payload_hash"),
    )
    op.create_index(
        op.f("ix_raw_payload_envelopes_publication_id"),
        "raw_payload_envelopes",
        ["publication_id"],
        unique=False,
    )
    op.create_table(
        "charging_stations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["charging_sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "external_id"),
    )
    op.create_index(
        op.f("ix_charging_stations_site_id"), "charging_stations", ["site_id"], unique=False
    )
    op.create_table(
        "detected_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("incident_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["publication_id"], ["source_publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["charging_sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detected_incidents_publication_id"),
        "detected_incidents",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detected_incidents_site_id"), "detected_incidents", ["site_id"], unique=False
    )
    op.create_table(
        "evses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("max_power_kw", sa.Float(), nullable=False),
        sa.Column("current_type", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["charging_stations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("station_id", "external_id"),
    )
    op.create_index(op.f("ix_evses_external_id"), "evses", ["external_id"], unique=False)
    op.create_index(op.f("ix_evses_station_id"), "evses", ["station_id"], unique=False)
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evse_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("connector_type", sa.String(length=64), nullable=False),
        sa.Column("max_power_kw", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["evse_id"], ["evses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evse_id", "external_id"),
    )
    op.create_index(op.f("ix_connectors_evse_id"), "connectors", ["evse_id"], unique=False)
    op.create_table(
        "price_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("per_kwh", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("per_minute", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("session_fee", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("blocking_fee", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_observations_connector_id"),
        "price_observations",
        ["connector_id"],
        unique=False,
    )
    op.create_table(
        "static_capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("capability", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_static_capabilities_connector_id"),
        "static_capabilities",
        ["connector_id"],
        unique=False,
    )
    op.create_table(
        "status_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_events_connector_id"), "status_events", ["connector_id"], unique=False
    )
    op.create_index(
        op.f("ix_status_events_started_at"), "status_events", ["started_at"], unique=False
    )
    op.create_table(
        "status_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), nullable=False),
        sa.Column("is_delta", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["source_publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "source_observed_at"),
        sa.UniqueConstraint(
            "publication_id",
            "connector_id",
            "source_observed_at",
            name="uq_status_observation_message",
        ),
        postgresql_partition_by="RANGE (source_observed_at)",
    )
    op.create_index(
        "ix_status_connector_observed_desc",
        "status_observations",
        ["connector_id", sa.literal_column("source_observed_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_status_observations_connector_id"),
        "status_observations",
        ["connector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_status_observations_publication_id"),
        "status_observations",
        ["publication_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE TABLE status_observations_2026_07
        PARTITION OF status_observations
        FOR VALUES FROM ('2026-07-01T00:00:00Z') TO ('2026-08-01T00:00:00Z')
        """
    )
    op.execute(
        """
        CREATE TABLE status_observations_default
        PARTITION OF status_observations DEFAULT
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_status_observations_publication_id"), table_name="status_observations")
    op.drop_index(op.f("ix_status_observations_connector_id"), table_name="status_observations")
    op.drop_index("ix_status_connector_observed_desc", table_name="status_observations")
    op.drop_table("status_observations")
    op.drop_index(op.f("ix_status_events_started_at"), table_name="status_events")
    op.drop_index(op.f("ix_status_events_connector_id"), table_name="status_events")
    op.drop_table("status_events")
    op.drop_index(op.f("ix_static_capabilities_connector_id"), table_name="static_capabilities")
    op.drop_table("static_capabilities")
    op.drop_index(op.f("ix_price_observations_connector_id"), table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index(op.f("ix_connectors_evse_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_evses_station_id"), table_name="evses")
    op.drop_index(op.f("ix_evses_external_id"), table_name="evses")
    op.drop_table("evses")
    op.drop_index(op.f("ix_detected_incidents_site_id"), table_name="detected_incidents")
    op.drop_index(op.f("ix_detected_incidents_publication_id"), table_name="detected_incidents")
    op.drop_table("detected_incidents")
    op.drop_index(op.f("ix_charging_stations_site_id"), table_name="charging_stations")
    op.drop_table("charging_stations")
    op.drop_index(
        op.f("ix_raw_payload_envelopes_publication_id"), table_name="raw_payload_envelopes"
    )
    op.drop_table("raw_payload_envelopes")
    op.drop_index(
        op.f("ix_feed_health_observations_publication_id"), table_name="feed_health_observations"
    )
    op.drop_index(
        op.f("ix_feed_health_observations_observed_at"), table_name="feed_health_observations"
    )
    op.drop_table("feed_health_observations")
    op.drop_index(op.f("ix_charging_sites_publication_id"), table_name="charging_sites")
    op.drop_index(op.f("ix_charging_sites_operator_id"), table_name="charging_sites")
    op.drop_index("ix_charging_sites_geom", table_name="charging_sites", postgresql_using="gist")
    op.drop_index(op.f("ix_charging_sites_data_mode"), table_name="charging_sites")
    op.drop_index(op.f("ix_charging_sites_bundesland"), table_name="charging_sites")
    op.drop_table("charging_sites")
    op.drop_index(op.f("ix_source_publications_data_source_id"), table_name="source_publications")
    op.drop_table("source_publications")
    op.drop_index(op.f("ix_operators_name"), table_name="operators")
    op.drop_table("operators")
    op.drop_index(op.f("ix_reliability_metrics_scope_id"), table_name="reliability_metrics")
    op.drop_table("reliability_metrics")
    op.drop_table("region_snapshots")
    op.drop_table("national_snapshots")
    op.drop_index(op.f("ix_data_sources_data_mode"), table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_table("data_licences")
    # ### end Alembic commands ###
